# Generated by Django 6.0.2 on 2026-03-13 11:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='cedula',
            field=models.CharField(default='0', max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='cedula',
            field=models.CharField(default='0', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='El teléfono debe tener 10 dígitos y empezar por el número 3.', regex='^3\\d{9}$')]),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='telefono',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='El teléfono debe tener 10 dígitos y empezar por el número 3.', regex='^3\\d{9}$')]),
        ),
    ]
