# Generated by Django 6.0.2 on 2026-03-16 12:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_cliente_cedula_empleado_cedula_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cedula',
            field=models.CharField(default='0', max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='La cédula solo puede contener números y no puede empezar en cero.', regex='^[1-9]\\d*$')]),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='cedula',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='La cédula solo puede contener números y no puede empezar en cero.', regex='^[1-9]\\d*$')]),
        ),
        migrations.AlterField(
            model_name='producto',
            name='cantidad',
            field=models.CharField(default='0', max_length=50),
        ),
    ]
