# Generated by Django 6.0.2 on 2026-03-22 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0005_insumo_remove_producto_cantidad_receta'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='duracion',
            field=models.PositiveIntegerField(default=2, verbose_name='Duración (horas)'),
        ),
    ]
