# Generated by Django 6.0.2 on 2026-03-24 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0007_categoria_producto_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='puesto',
            field=models.CharField(choices=[('mesero', 'Mesero'), ('cajero', 'Cajero'), ('administrador', 'Administrador')], max_length=50),
        ),
    ]
