# Generated by Django 6.0.2 on 2026-04-21 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0011_orden_factura_sucursal'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empleados', to='gestion.sucursal', verbose_name='Sucursal'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='metodo_pago',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('tarjeta', 'Tarjeta'), ('transferencia', 'Transferencia')], default='efectivo', max_length=20),
        ),
        migrations.AlterField(
            model_name='factura',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='facturas', to='gestion.sucursal'),
        ),
        migrations.AlterField(
            model_name='orden',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en_preparacion', 'En Preparación'), ('lista', 'Lista'), ('entregada', 'Entregada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='orden',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordenes', to='gestion.sucursal'),
        ),
    ]
