# Generated by Django 6.0.2 on 2026-04-22 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0014_alter_cliente_email'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='reserva',
            constraint=models.UniqueConstraint(fields=('mesa', 'fecha', 'hora'), name='uq_reserva_mesa_fecha_hora'),
        ),
    ]
