# Generated by Django 6.0.2 on 2026-04-22 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0015_reserva_uq_reserva_mesa_fecha_hora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en_preparacion', 'En Preparación'), ('lista', 'Lista'), ('pagada', 'Pagada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20),
        ),
    ]
