# Generated by Django 6.0.2 on 2026-04-25 05:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0016_alter_orden_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cedula',
            field=models.CharField(default='0', max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='La cédula solo puede contener números y no puede empezar en cero.', regex='^[1-9]\\d*$')]),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='cedula',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='La cédula solo puede contener números y no puede empezar en cero.', regex='^[1-9]\\d*$')]),
        ),
    ]
