# Generated by Django 6.0.2 on 2026-04-26 02:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0019_alter_categoria_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cedula',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='La cédula solo puede contener números y no puede empezar en cero.', regex='^[1-9]\\d*$')]),
        ),
    ]
