# Generated by Django 6.0.2 on 2026-04-28 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0020_alter_cliente_cedula'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='monto_recibido',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='factura',
            name='numero_aprobacion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='factura',
            name='numero_transferencia',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='factura',
            name='vuelto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
