# Generated by Django 6.0.2 on 2026-04-29 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0022_mesa_sucursal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mesa',
            options={'ordering': ['sucursal', 'numero'], 'verbose_name': 'Mesa', 'verbose_name_plural': 'Mesas'},
        ),
        migrations.AddField(
            model_name='empleado',
            name='apellido',
            field=models.CharField(default='', max_length=100, verbose_name='Apellido'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='empleado',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
    ]
