# Generated by Django 6.0.2 on 2026-04-29 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0024_alter_empleado_usuario_not_null'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='reserva',
            name='uq_reserva_mesa_fecha_hora',
        ),
    ]
