# Generated by Django 6.0.2 on 2026-04-30 23:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0026_mesa_sucursal_not_null'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='sucursal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='facturas', to='gestion.sucursal'),
        ),
        migrations.AlterField(
            model_name='orden',
            name='sucursal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes', to='gestion.sucursal'),
        ),
    ]
