# Generated by Django 6.0.2 on 2026-05-01 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0027_alter_factura_sucursal_alter_orden_sucursal'),
    ]

    operations = [
      
        migrations.AddField(
            model_name='cliente',
            name='numero_documento',
            field=models.CharField(default='', max_length=20, unique=True, verbose_name='Número de documento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='tipo_documento',
            field=models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('PPT', 'Permiso de Protección Temporal'), ('PEP', 'Permiso Especial de Permanencia'), ('CE', 'Cédula de Extranjería'), ('PA', 'Pasaporte')], default='CC', max_length=5, verbose_name='Tipo de documento'),
        ),
    ]
